# Generated by Django 3.2.16 on 2022-11-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=16, verbose_name='Request Method')),
                ('datetime', models.DateTimeField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['date'], name='core_reques_date_7c38be_idx'),
        ),
    ]
