# Generated by Django 3.2.16 on 2022-11-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221129_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-datetime'], 'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
    ]
